package com.tuandatcoder.trekkerbackend.enums;

public enum ActivityActionTypeEnum {
    LOGIN,
    LOGOUT,
    UPLOAD_PHOTO,
    UPDATE_PROFILE,
    CREATE_TRIP,
    DELETE_TRIP,
    LIKE,
    COMMENT,
    DELETE_ALBUM,
    CREATE_ALBUM,
    ADD_PHOTO_TO_ALBUM,
    REMOVE_PHOTO_FROM_ALBUM,
    DELETE_COMMENT,
    CREATE_FEATURE,
    DELETE_FEATURE,
    FOLLOW_USER,
    UNFOLLOW_USER,
    SEND_FRIEND_REQUEST,
    ACCEPT_FRIEND_REQUEST,
    DECLINE_FRIEND_REQUEST,
    UNFRIEND,
    CREATE_PLACE_CATEGORY,
    DELETE_PLACE_CATEGORY,
    DELETE_REVIEW,
    REVIEW_PLACE,



}
